polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

product/urls.py
from django.urls import path

from . import views

app_name = "product"

urlpatterns = [
    # ex: /product/
    path('', views.index, name='index'),
    
    # ex: /product/5/
    path('<int:device_id>/', views.detail, name='detail'),
    
    # ex: /product/5/results/
    path('<int:device_id>/results/', views.test_results, name='test_results'),
    
    # ex: /product/5/new/
    path('<int:device_id>/new/', views.new_entry, name='new_entry'),
]

solarPV/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('product/', include('product.urls')),    
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('courses/', include('courses.urls')),
    path('api/', include('courses.api.url', namespace='api')),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

product/models.py
from django.db import models

class Device(models.Model):
    def __str__(self):
        return self.manufacturer + " " + self.model_number
    manufacturer = models.CharField(max_length=200)
    model_number = models.CharField(max_length=200)
    


class Test_Results(models.Model):
    def __str__(self):
        return self.test_sequence + self.test_date
    product = models.ForeignKey(Device, on_delete=models.CASCADE)
    test_sequence = models.CharField(max_length=200)
    condition = models.CharField(max_length=200)
    test_date = models.DateTimeField('date tested')
    isc = models.FloatField(default=0)
    voc = models.FloatField(default=0)
    imp = models.FloatField(default=0)
    vmp = models.FloatField(default=0)
    ff = models.FloatField(default=0)
    pmp = models.FloatField(default=0)

product/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.views import generic

from .models import Device

def index(request):
    device_list = Device.objects.order_by('-model_number')[:5]
    context = {'device_list': device_list}
    return render(request, 'product/index.html',context)

class DetailView(generic.DetailView):
    model = Device
    template_name = 'polls/detail.html'

def detail(request, device_id):
    device_ins = get_object_or_404(Device, pk=device_id)
    return render(request, 'product/detail.html', {'device':device_ins})

def test_results(request, device_id):
    response = "You're looking at the results of device %s."
    return HttpResponse(response % device_id)

def new_entry(request, device_id):
    device_ins = get_object_or_404(Device, pk=device_id)
    return render(request, 'product/new.html', {'device':device_ins})

product/templates/product/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>    
    <link rel="stylesheet" type="text/css"
    href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>Product Test Results for {{ device.manufacturer }} - {{ device.model_number }}</h1>
    <ul>
    {% for choice in device.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>
</body>
</html>

product/templates/product/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>    
    <link rel="stylesheet" type="text/css"
    href="{% static 'css/style.css' %}">
</head>
    <body>
        <h1>testing</h1>
        <ul>
        {% for dev in device_list %}
            <li><a href="{% url 'product:detail' dev.id %}">{{ dev.manufacturer }} - {{ dev.model_number }}</a></li>
        {% endfor %}
        </ul>
    </body>
</html>

product/templates/product/new.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous">
    </script>
    <script src = jquery.js></script>
    
    <link rel="stylesheet" type="text/css"
    href="{% static 'css/style.css' %}">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <div class="container">
            <nav>
                <ul>
                    <li class=current><a href="login.html">Register/Login</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <section id="newsletter">
        <div class="container">
            <h1>Module Detailed Specifications</h1>
    
        </div>
    </section>
    <section id="main">
        <div class="container">
            <article id="main-col">
                <h1 class="page-title">Note: It can be assumed that with the exception of Model numbers, the specifications are the same for all modules in the test results</h1>
                  

            </article>

        </div>

    </section>

        <div class="container">
        
        <header>
          <h1>Please fill in the fields below</h1>
        </header>
    
        <form action="index.html" method="post">
                  
            <fieldset>         
                <legend>Specifications</legend>

                <label for="Model"> Model:</label><br>
                <input type="text" id="Model" name="model" placeholder="required">
                <p id ="Model-name-error"></p>

                <label for="Test_Sequence"> Test Sequence:</label><br>
                <input type="text" id="Test_Sequence" name="Test_Sequence" placeholder="required">
                <p id ="Test-sequence-name-error"></p>

                <label for="Condition"> Condition:</label><br>
                <input type="text" id="Condition" name="Condition"  placeholder="required">
                <p id ="Condition-name-error"></p>

                <label for="Date"> Date:</label><br>
                <input type="text" id="Date" name="Date"  placeholder="required">
                <p id ="Date-name-error"></p>
                
                <label for="ISC"> ISC:</label><br>
                <input type="text" id="ISC" name="ISC"  placeholder="required">
                <p id ="ISC-error"></p>

                <label for="VOC">VOC:</label><br>
                <input type="text" id="VOC" name="VOC"  placeholder="required">
                <p id = "VOC-error"></p>
                                    
                <label for="IMP">IMP:</label><br>
                <input type="text" id="IMP" name="IMP"  placeholder="required">
                <p id = "IMP-Error"></p>

                <label for="VMP">VMP:</label><br>
                <input type="text" id="VMP" name="VMP"  placeholder="required">
                <p id = "VMP-Error"></p>

                <label for="FF">FF:</label><br>
                <input type="text" id="FF" name="FF"  placeholder="required">
                <p id = "FF-Error"></p>

                <label for="PMP">PMP:</label><br>
                <input type="text" id="PMP" name="PMP" placeholder="required">
                <p id = "PMP-Error"></p>
    
            </fieldset>      
            
          <button type="submit" id = 'submitButton'>Register</button>
          <p id = 'fillOutAllFields'></p>
        </form>
    
      </div>

    <footer>
        <p>Solar Panel Company Copyright &copy; 2020</p>
    </footer>
</body>
</html>

product/templates/product/register.html
<!DOCTYPE html>
<html>
    <head>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous">
        </script>
        <script src = jqueryRegister.js></script>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <div class="container">
                <div id="branding">
                    <h1><span class=highlight>Register</span></h1>
                </div>
                <nav>
                    <ul>


                    </ul>
                </nav>
            </div>
        </header>

        <section id="newsletter">
            <div class="container">
                <h1>New or existing Clients</h1>
                <form>
                    <input type="email" placeholder="enter email">
                    <buttton type="submit" class="button_1">Subscribe</buttton>
                </form>
            </div>
        </section>
        <section id="main">
            <div class="container">
                <article id="main-col">
                    <h1 class="page-title">Already A Memeber</h1>
                    <form>
                        <label for="fname">UserName:</label><br>
                        <input type="text" id="userName" name="username" value=""><br>
                        <label for="lname">Password:</label><br>
                        <input type="text" id="passWord" name="password" value=""><br><br>
                        <input type="submit" value="Submit">
                      </form> 
                      

                </article>

            </div>

        </section>

        <body>
            <div class="container">
            
            <header>
              <span>Create A New Account to Help your local Neighborhood</span>
              <h1>Create New Account</h1>
            </header>
        
            <form action="index.html" method="post">
                      
                <fieldset>         
                    <legend>New Account Information</legend>

                    <label for="first-name"> First Name:</label><br>
                    <input type="text" id="first-name" name="first_name" placeholder="required">
                    <p id ="first-name-error"></p>

                    <label for="middle-name"> Middle Name:</label><br>
                    <input type="text" id="middle-name" name="middle_name" placeholder="optional">
                    <p id ="middle-name-error"></p>

                    <label for="last-name"> Last Name:</label><br>
                    <input type="text" id="last-name" name="last_name" placeholder="required">
                    <p id ="last-name-error"></p>

                    <label for="user-name"> UserName:</label><br>
                    <input type="text" id="user-name" name="user_name" placeholder="required">
                    <p id ="user-name-error"></p>
                    
                    <label for="create-password"> Create Password:</label><br>
                    <input type="text" id="create-password" name="create_password" placeholder="required">
                    <p id ="createPassword-error"></p>

                    <label for="mail">Email:</label><br>
                    <input type="email" id="mail" name="user_email" placeholder="required">
                    <p id = "mail-error"></p>

                    <label for="streetAddress">Street Address:</label><br>
                    <input type="text" id="street-address" name="street_address" placeholder="required">
                    <p id = "address-error"></p>

                    <label for="city">City:</label><br>
                    <input type="text" id="City" name="city" placeholder="required">
                    <p id = "city-error"></p>

                    <label for="state">State:</label><br>
                    <input type="text" id="State" name="state" placeholder="required">
                    <p id = "state-error"></p>

                    <label for="zip">Zip:</label><br>
                    <input type="text" id="Zip" name="zip" placeholder="required">
                    <p id = "zip-error"></p>

                    <label for="cell">Cell:</label><br>
                    <input type="text" id="Cell" name="cell" placeholder="optional">
                    <p id = "cell-error"></p>

                    <label for="cell">Office Number:</label><br>
                    <input type="text" id="office-number" name="office-number" placeholder="optional">
                    <p id = "cell-error"></p>
        
                </fieldset>      
                
              <button type="submit" id = 'submitButton'>Register</button>
              <p id = 'fillOutAllFields'></p>
            </form>
        
          </div>

        <footer>
            <p>Charity Copyright &copy; 2020</p>
        </footer>
    </body>
</html>